name: Build and Upload Portable App Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release_cli:
    strategy:
      fail-fast: false
      matrix:
        rid: [linux-arm64, linux-musl-arm64, linux-x64, linux-musl-x64, osx-x64, osx-arm64, win-x64, win-x86, win-arm64]
        build_configuration: [Release]
        deploy_mode: [with-runtime, no-runtime]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Build ASP.NET Core App
        run: |
          if [ "${{ matrix.deploy_mode }}" == "with-runtime" ]; then
            dotnet publish -c ${{ matrix.build_configuration }} -r ${{ matrix.rid }} TboxWebdav.Server.AspNetCore/TboxWebdav.Server.AspNetCore.csproj --self-contained
          else
            dotnet publish -c ${{ matrix.build_configuration }} -r ${{ matrix.rid }} TboxWebdav.Server.AspNetCore/TboxWebdav.Server.AspNetCore.csproj
          fi

      - name: Pack Release Asset
        run: |
          cd TboxWebdav.Server.AspNetCore/bin/${{ matrix.build_configuration }}/net8.0/${{ matrix.rid }}/publish/
          zip -r /tmp/TboxWebdav.Server.AspNetCore-${{ matrix.rid }}-${{ matrix.deploy_mode }}.zip .

      - name: Upload Release Asset
        env:
          GH_TOKEN: ${{ github.token }}
        run: >-
          gh release upload "${{ github.event.release.tag_name }}"
          "/tmp/TboxWebdav.Server.AspNetCore-${{ matrix.rid }}-${{ matrix.deploy_mode }}.zip"
          --clobber
